name: goloader Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:    
  build:
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: auto
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.18.x, 1.19.x, 1.20.x ]
        os:  [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Rename cmd/internal
      shell: sh
      run:
        cp -r $GOROOT/src/cmd/internal $GOROOT/src/cmd/objfile

    - name: Patch gc
      shell: sh
      run:
        go run github.com/eh-steve/goloader/jit/patchgc@WIP---Update-github-actions-to-run-tests

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    - name: Test
      shell: sh
      run:
        cd $GOPATH/src/github.com/eh-steve/goloader/jit && go test -c . && ./jit.test -test.v
